{"name": "Calories: Verify user is able to close the Nutrient add dialog with Close button.. -- @1.1 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//td[text()='Carbs']/following-sibling::td[1]\"}\n  (Session info: chrome=129.0.6668.58); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF7E0E3FDA5+29557]\n\t(No symbol) [0x00007FF7E0DB2240]\n\t(No symbol) [0x00007FF7E0C6B6EA]\n\t(No symbol) [0x00007FF7E0CBFA15]\n\t(No symbol) [0x00007FF7E0CBFC6C]\n\t(No symbol) [0x00007FF7E0D0BB07]\n\t(No symbol) [0x00007FF7E0CE753F]\n\t(No symbol) [0x00007FF7E0D088A3]\n\t(No symbol) [0x00007FF7E0CE72A3]\n\t(No symbol) [0x00007FF7E0CB12DF]\n\t(No symbol) [0x00007FF7E0CB2451]\n\tGetHandleVerifier [0x00007FF7E116DCBD+3363469]\n\tGetHandleVerifier [0x00007FF7E11B9B47+3674391]\n\tGetHandleVerifier [0x00007FF7E11AEAEB+3629243]\n\tGetHandleVerifier [0x00007FF7E0EFFC66+815670]\n\t(No symbol) [0x00007FF7E0DBD6EF]\n\t(No symbol) [0x00007FF7E0DB92B4]\n\t(No symbol) [0x00007FF7E0DB9450]\n\t(No symbol) [0x00007FF7E0DA81FF]\n\tBaseThreadInitThunk [0x00007FFD027C257D+29]\n\tRtlUserThreadStart [0x00007FFD0382AF28+40]\n\n", "trace": "  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\caloriescalc_steps.py\", line 79, in step_impl\n    actual_nutrient = context.driver.find_element(By.XPATH, CaloriesPageObjects.get_nutrient_value(nutrient_name)).text\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I navigate to homepage", "status": "passed", "start": 1726967477240, "stop": 1726967477255}, {"name": "When I enter username as \"testUser\"", "status": "passed", "start": 1726967477255, "stop": 1726967480392}, {"name": "And I enter password as \"Test1234\"", "status": "passed", "start": 1726967480392, "stop": 1726967483777}, {"name": "And I click on Continue button", "status": "passed", "start": 1726967483777, "stop": 1726967489669}, {"name": "And I click on Add Nutrient button on Home page", "status": "passed", "start": 1726967489669, "stop": 1726967492800}, {"name": "And I enter \"Carbs\" value as \"<Carbs>\"", "status": "passed", "start": 1726967492800, "stop": 1726967499168}, {"name": "And I verify \"Carbs\" got added with value \"<Carbs>\" on Nutrients Dashboard", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//td[text()='Carbs']/following-sibling::td[1]\"}\n  (Session info: chrome=129.0.6668.58); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF7E0E3FDA5+29557]\n\t(No symbol) [0x00007FF7E0DB2240]\n\t(No symbol) [0x00007FF7E0C6B6EA]\n\t(No symbol) [0x00007FF7E0CBFA15]\n\t(No symbol) [0x00007FF7E0CBFC6C]\n\t(No symbol) [0x00007FF7E0D0BB07]\n\t(No symbol) [0x00007FF7E0CE753F]\n\t(No symbol) [0x00007FF7E0D088A3]\n\t(No symbol) [0x00007FF7E0CE72A3]\n\t(No symbol) [0x00007FF7E0CB12DF]\n\t(No symbol) [0x00007FF7E0CB2451]\n\tGetHandleVerifier [0x00007FF7E116DCBD+3363469]\n\tGetHandleVerifier [0x00007FF7E11B9B47+3674391]\n\tGetHandleVerifier [0x00007FF7E11AEAEB+3629243]\n\tGetHandleVerifier [0x00007FF7E0EFFC66+815670]\n\t(No symbol) [0x00007FF7E0DBD6EF]\n\t(No symbol) [0x00007FF7E0DB92B4]\n\t(No symbol) [0x00007FF7E0DB9450]\n\t(No symbol) [0x00007FF7E0DA81FF]\n\tBaseThreadInitThunk [0x00007FFD027C257D+29]\n\tRtlUserThreadStart [0x00007FFD0382AF28+40]\n\n", "trace": "  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\caloriescalc_steps.py\", line 79, in step_impl\n    actual_nutrient = context.driver.find_element(By.XPATH, CaloriesPageObjects.get_nutrient_value(nutrient_name)).text\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "attachments": [{"name": "Screenshot", "source": "37f636a2-d7d2-472c-ab20-84bf53ebccbc-attachment.png", "type": "image/png"}], "start": 1726967499168, "stop": 1726967502370}, {"name": "And I click on Add Nutrient button on Home page", "status": "skipped", "start": 1726967504734, "stop": 1726967504734}, {"name": "And I update the \"Carbs\" value as \"2.2\"", "status": "skipped", "start": 1726967504734, "stop": 1726967504734}, {"name": "And I click on Close button to cancel the Nutrient value updates", "status": "skipped", "start": 1726967504734, "stop": 1726967504734}, {"name": "And I verify \"Carbs\" got added with value \"2.5\" on Nutrients Dashboard", "status": "skipped", "start": 1726967504734, "stop": 1726967504734}, {"name": "And I update the \"Carbs\" value as \"2.2\"", "status": "skipped", "start": 1726967504734, "stop": 1726967504734}, {"name": "And I click on Cancel button to cancel the Nutrient value updates", "status": "skipped", "start": 1726967504734, "stop": 1726967504734}, {"name": "And I verify \"Carbs\" got added with value \"2.5\" on Nutrients Dashboard", "status": "skipped", "start": 1726967504734, "stop": 1726967504734}, {"name": "Then I verify the Total Calories Values based on the formula", "status": "skipped", "start": 1726967504734, "stop": 1726967504734}], "parameters": [{"name": "userName", "value": "testUser"}, {"name": "passWord", "value": "Test1234"}, {"name": "orgCarbs", "value": "2.5"}, {"name": "newCarbs", "value": "2.2"}], "start": 1726967469874, "stop": 1726967504734, "uuid": "710c523f-9b31-405d-ad55-597ecdae68d8", "historyId": "ee633e647b33380fd49604e59e7b11b2", "fullName": "Calories Calculation functionality: Calories: Verify user is able to close the Nutrient add dialog with Close button..", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Calories"}, {"name": "tag", "value": "Regression"}, {"name": "tag", "value": "TC_CALC_04"}, {"name": "tag", "value": "noUpdates"}, {"name": "feature", "value": "Calories Calculation functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}